# Aula 03 - Prática Guiada em Sala
**Curso:** Programação para Ciência de Dados  
**Aluno:** [Seu Nome Aqui]  
**Data:** [Data Atual]

## Instruções
1. Estes exercícios serão feitos **durante a aula** com orientação do professor
2. Complete todos os exercícios marcados com `# === SEU CÓDIGO AQUI ===`
3. Execute as células de teste para verificar suas respostas
4. **Tempo estimado:** 5-7 minutos por exercício
5. **Não precisa submeter** - este é apenas para prática em aula

## Objetivo
Exercícios simples e diretos para fixar os conceitos básicos de NumPy.

In [1]:
# === CONFIGURAÇÃO INICIAL ===

# Atualizar pip e limpar cache
!pip install --upgrade pip --quiet
!pip cache purge

# Instalar Otter Grader
!pip install otter-grader --no-cache-dir -q

# Criar diretório para testes
!mkdir -p tests

print("Otter Grader instalado!")
print("Diretório de testes criado!")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 16.8 MB/s eta 0:00:00
Files removed: 6 (1.8 MB)
Otter Grader instalado!
Diretório de testes criado!


In [2]:
%%writefile tests/p1.py
OK_FORMAT = True

test = {
    "name": "p1",
    "points": 1,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Verificar se retorna array NumPy
>>> import numpy as np
>>> resultado = criar_array_notas()
>>> isinstance(resultado, np.ndarray)
True
""",
                    "hidden": False,
                    "locked": False
                },
                {
                    "code": r"""
>>> # Teste 2: Verificar shape (10 elementos)
>>> import numpy as np
>>> resultado = criar_array_notas()
>>> resultado.shape == (10,)
True
""",
                    "hidden": False,
                    "locked": False
                },
                {
                    "code": r"""
>>> # Teste 3: Verificar tipo float
>>> import numpy as np
>>> resultado = criar_array_notas()
>>> resultado.dtype in [np.float64, np.float32]
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/p1.py


In [3]:
%%writefile tests/p2.py
OK_FORMAT = True

test = {
    "name": "p2",
    "points": 1,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Verificar se retorna array
>>> import numpy as np
>>> arr = np.array([[1, 2, 3], [4, 5, 6]])
>>> resultado = extrair_segunda_coluna(arr)
>>> isinstance(resultado, np.ndarray)
True
""",
                    "hidden": False,
                    "locked": False
                },
                {
                    "code": r"""
>>> # Teste 2: Valores corretos
>>> import numpy as np
>>> arr = np.array([[1, 2, 3], [4, 5, 6]])
>>> resultado = extrair_segunda_coluna(arr)
>>> np.array_equal(resultado, np.array([2, 5]))
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/p2.py


In [4]:
%%writefile tests/p3.py
OK_FORMAT = True

test = {
    "name": "p3",
    "points": 1,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Filtrar valores maiores que 7
>>> import numpy as np
>>> arr = np.array([5, 8, 3, 9, 2, 10])
>>> resultado = filtrar_maiores(arr, 7)
>>> np.array_equal(resultado, np.array([8, 9, 10]))
True
""",
                    "hidden": False,
                    "locked": False
                },
                {
                    "code": r"""
>>> # Teste 2: Retorna array NumPy
>>> import numpy as np
>>> arr = np.array([1, 2, 3])
>>> resultado = filtrar_maiores(arr, 0)
>>> isinstance(resultado, np.ndarray)
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/p3.py


In [5]:
%%writefile tests/p4.py
OK_FORMAT = True

test = {
    "name": "p4",
    "points": 1,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Broadcasting correto
>>> import numpy as np
>>> matriz = np.array([[1, 2], [3, 4]])
>>> vetor = np.array([10, 20])
>>> resultado = somar_com_broadcasting(matriz, vetor)
>>> np.array_equal(resultado, np.array([[11, 22], [13, 24]]))
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/p4.py


In [6]:
%%writefile tests/p5.py
OK_FORMAT = True

test = {
    "name": "p5",
    "points": 1,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Calcular média
>>> import numpy as np
>>> arr = np.array([2, 4, 6, 8, 10])
>>> resultado = calcular_media(arr)
>>> abs(resultado - 6.0) < 0.01
True
""",
                    "hidden": False,
                    "locked": False
                },
                {
                    "code": r"""
>>> # Teste 2: Retorna float
>>> import numpy as np
>>> arr = np.array([1, 2, 3])
>>> resultado = calcular_media(arr)
>>> isinstance(resultado, (float, np.floating))
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/p5.py


In [7]:
%%writefile tests/p6.py
OK_FORMAT = True

test = {
    "name": "p6",
    "points": 1,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Soma por linha
>>> import numpy as np
>>> matriz = np.array([[1, 2], [3, 4]])
>>> resultado = somar_linhas(matriz)
>>> np.array_equal(resultado, np.array([3, 7]))
True
""",
                    "hidden": False,
                    "locked": False
                },
                {
                    "code": r"""
>>> # Teste 2: Shape correto
>>> import numpy as np
>>> matriz = np.array([[1, 2, 3], [4, 5, 6]])
>>> resultado = somar_linhas(matriz)
>>> resultado.shape == (2,)
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/p6.py


In [8]:
%%writefile tests/p7.py
OK_FORMAT = True

test = {
    "name": "p7",
    "points": 1,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Substituir valores
>>> import numpy as np
>>> arr = np.array([1, 5, 3, 8, 2])
>>> resultado = substituir_com_where(arr, 5, 100, 0)
>>> np.array_equal(resultado, np.array([0, 100, 0, 100, 0]))
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/p7.py


In [9]:
%%writefile tests/p8.py
OK_FORMAT = True

test = {
    "name": "p8",
    "points": 1,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Retorna dicionário
>>> import numpy as np
>>> arr = np.arange(100)
>>> resultado = comparar_performance(arr)
>>> isinstance(resultado, dict)
True
""",
                    "hidden": False,
                    "locked": False
                },
                {
                    "code": r"""
>>> # Teste 2: Chaves corretas
>>> import numpy as np
>>> arr = np.arange(100)
>>> resultado = comparar_performance(arr)
>>> 'tempo_loop' in resultado and 'tempo_vetorizado' in resultado
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/p8.py


In [10]:
# === CARREGAR OTTER GRADER ===

import otter
grader = otter.Notebook()

print("Otter Grader configurado!")
print(f"Versão: {otter.__version__}")
print("\nTestes públicos carregados: p1.py, p2.py, p3.py, p4.py, p5.py, p6.py, p7.py, p8.py")
print("\nPrática guiada NumPy - exercícios simples para fixação!")

Otter Grader configurado!
Versão: 6.1.6

Testes públicos carregados: p1.py, p2.py, p3.py, p4.py, p5.py, p6.py, p7.py, p8.py

Prática guiada NumPy - exercícios simples para fixação!


In [11]:
# === IMPORTAR NUMPY ===

import numpy as np
import time

# Configurar exibição
np.set_printoptions(precision=2, suppress=True)

print(f"✓ NumPy versão: {np.__version__}")
print("✓ Pronto para começar!")

✓ NumPy versão: 2.0.2
✓ Pronto para começar!


# === PRÁTICA 1: CRIAÇÃO DE ARRAYS ===

## Objetivo
Criar arrays NumPy de diferentes formas.

## Tarefa
Criar um array com 10 notas aleatórias entre 0 e 10 usando `np.random.uniform()`.

## Retorno Esperado
Array 1D com 10 elementos float entre 0 e 10.

## Dicas
```python
# Criar array de valores aleatórios
arr = np.random.uniform(min, max, quantidade)

# Exemplo
arr = np.random.uniform(0, 100, 5)  # 5 valores entre 0 e 100
```

In [12]:
def criar_array_notas():
    """
    Cria array com 10 notas aleatórias entre 0 e 10.

    Returns:
        np.ndarray: Array com 10 notas
    """
    # === SEU CÓDIGO AQUI ===

    # Fixar seed para reprodutibilidade
    np.random.seed(42)

    # Criar array com 10 valores entre 0 e 10
    notas = np.random.uniform(0, 10, 10)

    return notas

    # === FIM DO SEU CÓDIGO ===

In [13]:
# Testar sua função
notas = criar_array_notas()

print("\n=== ARRAY DE NOTAS ===")
print(f"Array: {notas}")
print(f"\nShape: {notas.shape}")
print(f"Dtype: {notas.dtype}")
print(f"Tamanho: {notas.size} elementos")
print(f"\nMédia: {notas.mean():.2f}")
print(f"Maior nota: {notas.max():.2f}")
print(f"Menor nota: {notas.min():.2f}")

# Verificar teste
grader.check("p1")


=== ARRAY DE NOTAS ===
Array: [3.75 9.51 7.32 5.99 1.56 1.56 0.58 8.66 6.01 7.08]

Shape: (10,)
Dtype: float64
Tamanho: 10 elementos

Média: 5.20
Maior nota: 9.51
Menor nota: 0.58


p1 results: All test cases passed!

# === PRÁTICA 2: INDEXAÇÃO E SLICING ===

## Objetivo
Extrair dados usando indexação multidimensional.

## Tarefa
Extrair a **segunda coluna** de uma matriz 2D.

## Retorno Esperado
Array 1D com todos os valores da coluna índice 1.

## Dicas
```python
# Acessar linha
matriz[0]      # Primeira linha
matriz[0, :]   # Primeira linha (explícito)

# Acessar coluna
matriz[:, 0]   # Primeira coluna
matriz[:, 1]   # Segunda coluna

# Elemento específico
matriz[linha, coluna]
```

In [14]:
def extrair_segunda_coluna(matriz):
    """
    Extrai a segunda coluna (índice 1) de uma matriz.

    Args:
        matriz (np.ndarray): Matriz 2D

    Returns:
        np.ndarray: Array 1D com valores da segunda coluna
    """
    # === SEU CÓDIGO AQUI ===

    # Extrair coluna de índice 1
    coluna = matriz[:, 1]

    return coluna

    # === FIM DO SEU CÓDIGO ===

In [15]:
# Criar matriz de exemplo
matriz_vendas = np.array([
    [100, 150, 200],  # Produto A
    [80, 120, 160],   # Produto B
    [90, 110, 140]    # Produto C
])

print("\n=== MATRIZ DE VENDAS (3 produtos x 3 meses) ===")
print(matriz_vendas)
print("\nColunas: Jan, Fev, Mar")

# Extrair segunda coluna (Fevereiro)
vendas_fev = extrair_segunda_coluna(matriz_vendas)

print("\n=== VENDAS DE FEVEREIRO ===")
print(f"Produto A: {vendas_fev[0]}")
print(f"Produto B: {vendas_fev[1]}")
print(f"Produto C: {vendas_fev[2]}")
print(f"\nTotal: {vendas_fev.sum()}")

# Verificar teste
grader.check("p2")


=== MATRIZ DE VENDAS (3 produtos x 3 meses) ===
[[100 150 200]
 [ 80 120 160]
 [ 90 110 140]]

Colunas: Jan, Fev, Mar

=== VENDAS DE FEVEREIRO ===
Produto A: 150
Produto B: 120
Produto C: 110

Total: 380


p2 results: All test cases passed!

# === PRÁTICA 3: BOOLEAN INDEXING ===

## Objetivo
Filtrar array usando condições booleanas.

## Tarefa
Filtrar apenas valores **maiores** que um limiar especificado.

## Retorno Esperado
Array com apenas os valores que atendem à condição.

## Dicas
```python
# Criar máscara booleana
mask = arr > 5

# Aplicar máscara
resultado = arr[mask]

# Forma compacta
resultado = arr[arr > 5]
```

In [16]:
def filtrar_maiores(arr, limiar):
    """
    Filtra valores maiores que o limiar.

    Args:
        arr (np.ndarray): Array de entrada
        limiar (float): Valor de corte

    Returns:
        np.ndarray: Array com valores > limiar
    """
    # === SEU CÓDIGO AQUI ===

    # Aplicar filtro booleano
    resultado = arr[arr > limiar]

    return resultado

    # === FIM DO SEU CÓDIGO ===

In [17]:
# Criar dados de temperatura
np.random.seed(42)
temperaturas = np.random.uniform(15, 35, 20)

print("\n=== TEMPERATURAS (20 medições) ===")
print(f"Todas: {temperaturas}")
print(f"\nMédia: {temperaturas.mean():.1f}°C")

# Filtrar temperaturas altas (> 28°C)
temp_altas = filtrar_maiores(temperaturas, 28)

print("\n=== TEMPERATURAS ALTAS (> 28°C) ===")
print(f"Valores: {temp_altas}")
print(f"Quantidade: {len(temp_altas)} medições")
print(f"Percentual: {len(temp_altas)/len(temperaturas)*100:.1f}%")

# Verificar teste
grader.check("p3")


=== TEMPERATURAS (20 medições) ===
Todas: [22.49 34.01 29.64 26.97 18.12 18.12 16.16 32.32 27.02 29.16 15.41 34.4
 31.65 19.25 18.64 18.67 21.08 25.5  23.64 20.82]

Média: 24.2°C

=== TEMPERATURAS ALTAS (> 28°C) ===
Valores: [34.01 29.64 32.32 29.16 34.4  31.65]
Quantidade: 6 medições
Percentual: 30.0%


p3 results: All test cases passed!

# === PRÁTICA 4: BROADCASTING ===

## Objetivo
Realizar operações entre arrays de shapes diferentes.

## Tarefa
Somar uma matriz 2D com um vetor 1D usando broadcasting.

## Retorno Esperado
Matriz onde cada linha foi somada com o vetor.

## Dicas
```python
# Broadcasting automático
matriz = np.array([[1, 2], [3, 4]])  # (2, 2)
vetor = np.array([10, 20])            # (2,)

# Soma com broadcasting
resultado = matriz + vetor
# [[11, 22],
#  [13, 24]]
```

In [18]:
def somar_com_broadcasting(matriz, vetor):
    """
    Soma matriz 2D com vetor 1D usando broadcasting.

    Args:
        matriz (np.ndarray): Matriz 2D
        vetor (np.ndarray): Vetor 1D

    Returns:
        np.ndarray: Resultado da soma
    """
    # === SEU CÓDIGO AQUI ===

    # Broadcasting automático
    resultado = matriz + vetor

    return resultado

    # === FIM DO SEU CÓDIGO ===

In [19]:
# Dados: vendas por produto e mês
vendas = np.array([
    [100, 150, 200],  # Produto A
    [80, 120, 160],   # Produto B
    [90, 110, 140]    # Produto C
])

# Bônus mensal a adicionar
bonus = np.array([10, 20, 30])  # Jan, Fev, Mar

print("\n=== VENDAS ORIGINAIS ===")
print(vendas)
print(f"Shape: {vendas.shape}")

print("\n=== BÔNUS MENSAL ===")
print(bonus)
print(f"Shape: {bonus.shape}")

# Aplicar bônus usando broadcasting
vendas_com_bonus = somar_com_broadcasting(vendas, bonus)

print("\n=== VENDAS COM BÔNUS ===")
print(vendas_com_bonus)
print("\n💡 Broadcasting somou o vetor a cada linha da matriz!")

# Verificar teste
grader.check("p4")


=== VENDAS ORIGINAIS ===
[[100 150 200]
 [ 80 120 160]
 [ 90 110 140]]
Shape: (3, 3)

=== BÔNUS MENSAL ===
[10 20 30]
Shape: (3,)

=== VENDAS COM BÔNUS ===
[[110 170 230]
 [ 90 140 190]
 [100 130 170]]

💡 Broadcasting somou o vetor a cada linha da matriz!


p4 results: All test cases passed!

# === PRÁTICA 5: OPERAÇÕES VETORIZADAS ===

## Objetivo
Usar funções NumPy em vez de loops.

## Tarefa
Calcular a média de um array usando `np.mean()`.

## Retorno Esperado
Valor float com a média.

## Dicas
```python
# Funções de agregação
np.mean(arr)   # Média
np.sum(arr)    # Soma
np.std(arr)    # Desvio padrão
np.min(arr)    # Mínimo
np.max(arr)    # Máximo
```

In [28]:
def calcular_media(arr):
    """
    Calcula a média de um array.

    Args:
        arr (np.ndarray): Array de entrada

    Returns:
        float: Média dos valores
    """
    # === SEU CÓDIGO AQUI ===

    # Calcular média usando NumPy
    media = np.mean(arr)

    return float(media)

    # === FIM DO SEU CÓDIGO ===

In [29]:
# Usar notas da Prática 1
notas = criar_array_notas()

print("\n=== ESTATÍSTICAS DAS NOTAS ===")
print(f"Notas: {notas}")

# Calcular média
media = calcular_media(notas)
print(f"\nMédia: {media:.2f}")

# Outras estatísticas (demonstração)
print(f"Mediana: {np.median(notas):.2f}")
print(f"Desvio padrão: {np.std(notas):.2f}")
print(f"Nota máxima: {np.max(notas):.2f}")
print(f"Nota mínima: {np.min(notas):.2f}")

# Verificar teste
grader.check("p5")


=== ESTATÍSTICAS DAS NOTAS ===
Notas: [3.75 9.51 7.32 5.99 1.56 1.56 0.58 8.66 6.01 7.08]

Média: 5.20
Mediana: 6.00
Desvio padrão: 3.00
Nota máxima: 9.51
Nota mínima: 0.58


p5 results: All test cases passed!

# === PRÁTICA 6: OPERAÇÕES COM AXIS ===

## Objetivo
Aplicar agregações em dimensões específicas.

## Tarefa
Calcular a soma de cada **linha** de uma matriz (axis=1).

## Retorno Esperado
Array 1D com a soma de cada linha.

## Dicas
```python
# Sem axis: opera em tudo
np.sum(matriz)  # Soma total

# axis=0: ao longo das linhas (colapsa linhas)
np.sum(matriz, axis=0)  # Soma de cada coluna

# axis=1: ao longo das colunas (colapsa colunas)
np.sum(matriz, axis=1)  # Soma de cada linha
```

In [22]:
def somar_linhas(matriz):
    """
    Calcula a soma de cada linha.

    Args:
        matriz (np.ndarray): Matriz 2D

    Returns:
        np.ndarray: Array com soma de cada linha
    """
    # === SEU CÓDIGO AQUI ===

    # Somar ao longo do axis=1 (colunas)
    somas = np.sum(matriz, axis=1)

    return somas

    # === FIM DO SEU CÓDIGO ===

In [23]:
# Matriz de vendas trimestrais
vendas_trimestre = np.array([
    [100, 150, 200, 180],  # Produto A
    [80, 120, 160, 140],   # Produto B
    [90, 110, 140, 130]    # Produto C
])

print("\n=== VENDAS POR TRIMESTRE ===")
print("Produtos (linhas) x Meses (colunas)")
print(vendas_trimestre)

# Calcular total por produto
total_por_produto = somar_linhas(vendas_trimestre)

print("\n=== TOTAL POR PRODUTO (4 meses) ===")
produtos = ['Produto A', 'Produto B', 'Produto C']
for i, produto in enumerate(produtos):
    print(f"{produto}: {total_por_produto[i]}")

# Demonstrar axis=0 também
print("\n=== TOTAL POR MÊS (axis=0) ===")
total_por_mes = np.sum(vendas_trimestre, axis=0)
meses = ['Mês 1', 'Mês 2', 'Mês 3', 'Mês 4']
for i, mes in enumerate(meses):
    print(f"{mes}: {total_por_mes[i]}")

# Verificar teste
grader.check("p6")


=== VENDAS POR TRIMESTRE ===
Produtos (linhas) x Meses (colunas)
[[100 150 200 180]
 [ 80 120 160 140]
 [ 90 110 140 130]]

=== TOTAL POR PRODUTO (4 meses) ===
Produto A: 630
Produto B: 500
Produto C: 470

=== TOTAL POR MÊS (axis=0) ===
Mês 1: 270
Mês 2: 380
Mês 3: 500
Mês 4: 450


p6 results: All test cases passed!

# === PRÁTICA 7: np.where() ===

## Objetivo
Usar `np.where()` para seleção condicional.

## Tarefa
Substituir valores maiores que um limiar por um valor, e menores por outro.

## Retorno Esperado
Array com valores substituídos conforme condição.

## Dicas
```python
# np.where(condição, valor_se_true, valor_se_false)

arr = np.array([1, 5, 3, 8, 2])

# Se > 5 então 'alto', senão 'baixo'
resultado = np.where(arr >= 5, 'alto', 'baixo')

# Pode usar os próprios valores
resultado = np.where(arr >= 5, arr * 10, arr)
```

In [30]:
def substituir_com_where(arr, limiar, valor_alto, valor_baixo):
    """
    Substitui valores usando np.where().

    Args:
        arr (np.ndarray): Array de entrada
        limiar (float): Valor de corte
        valor_alto: Valor para elementos > limiar
        valor_baixo: Valor para elementos <= limiar

    Returns:
        np.ndarray: Array com valores substituídos
    """
    # === SEU CÓDIGO AQUI ===

    # Usar np.where para substituir
    resultado = np.where(arr >= limiar, valor_alto, valor_baixo)

    return resultado

    # === FIM DO SEU CÓDIGO ===

In [31]:
# Dados de temperatura
np.random.seed(42)
temperaturas = np.random.uniform(15, 35, 10)

print("\n=== CLASSIFICAÇÃO DE TEMPERATURAS ===")
print(f"Originais: {temperaturas}")

# Classificar: > 25°C = 'quente', <= 25°C = 'frio'
classificacao = substituir_com_where(temperaturas, 25, 'quente', 'frio')

print("\n=== RESULTADO ===")
for i, (temp, classe) in enumerate(zip(temperaturas, classificacao)):
    print(f"Medição {i+1}: {temp:.1f}°C → {classe}")

# Contar quantos de cada
print(f"\nQuentes: {np.sum(classificacao == 'quente')}")
print(f"Frios: {np.sum(classificacao == 'frio')}")

# Verificar teste
grader.check("p7")


=== CLASSIFICAÇÃO DE TEMPERATURAS ===
Originais: [22.49 34.01 29.64 26.97 18.12 18.12 16.16 32.32 27.02 29.16]

=== RESULTADO ===
Medição 1: 22.5°C → frio
Medição 2: 34.0°C → quente
Medição 3: 29.6°C → quente
Medição 4: 27.0°C → quente
Medição 5: 18.1°C → frio
Medição 6: 18.1°C → frio
Medição 7: 16.2°C → frio
Medição 8: 32.3°C → quente
Medição 9: 27.0°C → quente
Medição 10: 29.2°C → quente

Quentes: 6
Frios: 4


p7 results: All test cases passed!

# === PRÁTICA 8: COMPARAÇÃO DE DESEMPENHO ===

## Objetivo
Comparar desempenho de loop vs vetorização.

## Tarefa
Medir tempo de execução de:
1. Loop Python para elevar ao quadrado
2. Operação vetorizada NumPy

## Retorno Esperado
Dicionário com tempos de execução.

## Dicas
```python
import time

# Medir tempo
start = time.time()
# ... código ...
tempo = time.time() - start

# Loop
resultado = []
for x in arr:
    resultado.append(x ** 2)

# Vetorizado
resultado = arr ** 2
```

In [26]:
def comparar_performance(arr):
    """
    Compara performance de loop vs vetorização.

    Args:
        arr (np.ndarray): Array de entrada

    Returns:
        dict: Tempos de execução
    """
    # === SEU CÓDIGO AQUI ===

    # Método 1: Loop Python
    start = time.time()
    resultado_loop = []
    for x in arr:
        resultado_loop.append(x ** 2)
    tempo_loop = time.time() - start

    # Método 2: Vetorizado
    start = time.time()
    resultado_vetorizado = arr ** 2
    tempo_vetorizado = time.time() - start

    return {
        'tempo_loop': tempo_loop,
        'tempo_vetorizado': tempo_vetorizado,
        'speedup': tempo_loop / tempo_vetorizado if tempo_vetorizado > 0 else 0
    }

    # === FIM DO SEU CÓDIGO ===

In [27]:
# Testar com diferentes tamanhos

print("\n=== COMPARAÇÃO DE PERFORMANCE ===\n")

tamanhos = [1000, 10000, 100000]

for n in tamanhos:
    arr = np.arange(n)
    resultado = comparar_performance(arr)

    print(f"📊 Array com {n:,} elementos:")
    print(f"   Loop:       {resultado['tempo_loop']:.6f}s")
    print(f"   Vetorizado: {resultado['tempo_vetorizado']:.6f}s")
    print(f"   Speedup:    {resultado['speedup']:.1f}x mais rápido")
    print()

print("💡 NumPy é MUITO mais rápido que loops Python!")
print("   Sempre prefira operações vetorizadas.")

# Verificar teste
grader.check("p8")


=== COMPARAÇÃO DE PERFORMANCE ===

📊 Array com 1,000 elementos:
   Loop:       0.000314s
   Vetorizado: 0.000032s
   Speedup:    9.7x mais rápido

📊 Array com 10,000 elementos:
   Loop:       0.002702s
   Vetorizado: 0.000090s
   Speedup:    30.1x mais rápido

📊 Array com 100,000 elementos:
   Loop:       0.027925s
   Vetorizado: 0.000839s
   Speedup:    33.3x mais rápido

💡 NumPy é MUITO mais rápido que loops Python!
   Sempre prefira operações vetorizadas.


p8 results: All test cases passed!

# === RESUMO DA PRÁTICA GUIADA ===

## Conceitos Praticados

### Prática 1 - Criação de Arrays
- Criar arrays com `np.random.uniform()`
- Verificar shape, dtype, size
- Funções básicas de estatística

### Prática 2 - Indexação e Slicing
- Indexação multidimensional `arr[linha, coluna]`
- Extrair linhas e colunas inteiras
- Diferença entre `arr[i, j]` e `arr[i][j]`

### Prática 3 - Boolean Indexing
- Criar máscaras booleanas
- Filtrar dados com condições
- Análise estatística de subconjuntos

### Prática 4 - Broadcasting
- Operações entre arrays de shapes diferentes
- Broadcasting automático
- Eficiência vs loops manuais

### Prática 5 - Operações Vetorizadas
- Funções de agregação: mean, sum, std
- Vantagens sobre loops Python
- Código mais limpo e eficiente

### Prática 6 - Operações com Axis
- Conceito de axis=0 e axis=1
- Agregações por linha ou coluna
- Colapsar dimensões específicas

### Prática 7 - np.where()
- Seleção condicional
- Substituir valores baseado em condição
- Classificação de dados

### Prática 8 - Performance
- Medir tempo de execução
- Comparar loop vs vetorização
- Importância da escolha de abordagem

---

## Próximos Passos

Agora você está pronto para:
1. Fazer os exercícios da **prática independente** (mais complexos)
2. Trabalhar com arrays multidimensionais
3. Aplicar NumPy em análise de dados reais
4. Usar NumPy como base para Pandas

---

## Conceitos-Chave para Lembrar

- **Arrays são homogêneos** - todos elementos mesmo tipo
- **Slicing cria views** - modificações afetam original
- **Broadcasting** - operações automáticas entre shapes
- **Vetorização > Loops** - sempre prefira operações vetorizadas
- **axis=0 → linhas, axis=1 → colunas**
- **Boolean indexing** - poderoso para filtragem
- **NumPy é 10-100x mais rápido** que Python puro

**Bom trabalho!**