# Aula 03 - NumPy: Fundamentos
**Curso:** Programação para Ciência de Dados  
**Aluno:** Gisele Fonseca
**Data:** 14 de Out.

## Instruções
1. Complete todos os exercícios marcados com `# === SEU CÓDIGO AQUI ===`
2. Execute as células de teste para verificar suas respostas
3. **Tempo estimado total:** 30 minutos

## Critérios de Avaliação
- **Conteúdo (100%):** Testes automáticos

## Objetivo
Consolidar conhecimentos fundamentais de NumPy através de exercícios práticos.


In [1]:
# === CONFIGURAÇÃO INICIAL ===

!pip install --upgrade pip --quiet
!pip cache purge
!pip install otter-grader --no-cache-dir -q
!mkdir -p tests

print("Ambiente configurado!")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 34.2 MB/s eta 0:00:00
Files removed: 6 (1.8 MB)
Ambiente configurado!


In [2]:
%%writefile tests/q1.py
OK_FORMAT = True

test = {
    "name": "q1",
    "points": 2,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Retorna array NumPy
>>> import numpy as np
>>> resultado = criar_matriz_identidade(3)
>>> isinstance(resultado, np.ndarray)
True
""",
                    "hidden": False,
                    "locked": False
                },
                {
                    "code": r"""
>>> # Teste 2: Valores corretos na diagonal
>>> import numpy as np
>>> resultado = criar_matriz_identidade(3)
>>> np.array_equal(resultado, np.eye(3))
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/q1.py


In [3]:
%%writefile tests/q2.py
OK_FORMAT = True

test = {
    "name": "q2",
    "points": 3,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Normaliza corretamente
>>> import numpy as np
>>> arr = np.array([1, 2, 3, 4, 5])
>>> norm = normalizar_array(arr)
>>> bool(abs(norm.mean()) < 0.01 and abs(norm.std() - 1.0) < 0.01)
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/q2.py


In [4]:
%%writefile tests/q3.py
OK_FORMAT = True

test = {
    "name": "q3",
    "points": 3,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Substitui valores fora do intervalo
>>> import numpy as np
>>> arr = np.array([1, 5, 10, 15, 20])
>>> resultado = clipar_valores(arr, 5, 15)
>>> np.array_equal(resultado, np.array([5, 5, 10, 15, 15]))
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/q3.py


In [5]:
%%writefile tests/q4.py
OK_FORMAT = True

test = {
    "name": "q4",
    "points": 2,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Encontra índices corretos
>>> import numpy as np
>>> matriz = np.array([[1, 5, 3], [4, 2, 6]])
>>> idx = encontrar_indices_maximos(matriz)
>>> len(idx) == 2 and isinstance(idx[0], (int, np.integer))
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/q4.py


In [6]:
import otter
import numpy as np

grader = otter.Notebook()
np.random.seed(42)

print("✓ Otter Grader carregado")
print("✓ NumPy importado")
print(f"✓ Versão NumPy: {np.__version__}")

✓ Otter Grader carregado
✓ NumPy importado
✓ Versão NumPy: 2.0.2


# Exercício 1: Matriz Identidade

## Descrição
Crie uma função que gera uma matriz identidade de tamanho n×n.
Uma matriz identidade tem 1s na diagonal principal e 0s em todas as outras posições.

## Exemplo
```python
criar_matriz_identidade(3)
# [[1, 0, 0],
#  [0, 1, 0],
#  [0, 0, 1]]
```

## Dica
Use `np.eye()` ou `np.identity()`

**Tempo estimado:** 3 minutos

In [7]:
def criar_matriz_identidade(n):
    """
    Cria matriz identidade n×n.

    Args:
        n (int): Tamanho da matriz

    Returns:
        np.ndarray: Matriz identidade
    """
    # === SEU CÓDIGO AQUI ===

import numpy as np

def criar_matriz_identidade(n):
    """Cria matriz identidade n×n."""
    return np.eye(n)

    # === FIM DO SEU CÓDIGO ===



In [8]:
# Testar sua função
print("=== TESTE Q1 ===")
resultado = criar_matriz_identidade(4)
print(resultado)
print(f"\nShape: {resultado.shape}")

grader.check("q1")

=== TESTE Q1 ===
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Shape: (4, 4)


q1 results: All test cases passed!

# Exercício 2: Normalização Z-Score

## Descrição
Implemente normalização Z-score: subtraia a média e divida pelo desvio padrão.
A fórmula é: z = (x - μ) / σ

Onde:

- x = array original de entrada
- μ (mi) = média do array → use np.mean(arr)
- σ (sigma) = desvio padrão do array → use np.std(arr)
- z = array normalizado (resultado)

O resultado deve ter média ≈ 0 e desvio padrão ≈ 1.

## Exemplo
```python
arr = np.array([1, 2, 3, 4, 5])
normalizar_array(arr)
# array([-1.41, -0.71,  0.  ,  0.71,  1.41])
```

## Dicas
- Use `np.mean()` e `np.std()`
- Operações vetorizadas: `(arr - mean) / std`

**Tempo estimado:** 5 minutos

In [9]:
def normalizar_array(arr):
    """
    Normaliza array usando Z-score.

    Args:
        arr (np.ndarray): Array de entrada

    Returns:
        np.ndarray: Array normalizado
    """
    # === SEU CÓDIGO AQUI ===
def normalizar_array(arr):
    """Normaliza um array NumPy (z-score)."""
    media = arr.mean()
    desvio = arr.std()
    return (arr - media) / desvio


    # === FIM DO SEU CÓDIGO ===


In [10]:
# Testar sua função
print("=== TESTE Q2 ===")
arr = np.array([10, 20, 30, 40, 50])
norm = normalizar_array(arr)
print(f"Original: {arr}")
print(f"Normalizado: {norm}")
print(f"\nMédia: {norm.mean():.6f} (deve ser ~0)")
print(f"Desvio padrão: {norm.std():.6f} (deve ser ~1)")

grader.check("q2")

=== TESTE Q2 ===
Original: [10 20 30 40 50]
Normalizado: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

Média: 0.000000 (deve ser ~0)
Desvio padrão: 1.000000 (deve ser ~1)


q2 results: All test cases passed!

# Exercício 3: Clipping de Valores

## Descrição
Implemente uma função que limita valores de um array a um intervalo [min_val, max_val].
Valores menores que min_val devem ser substituídos por min_val.
Valores maiores que max_val devem ser substituídos por max_val.

## Exemplo
```python
arr = np.array([1, 5, 10, 15, 20])
clipar_valores(arr, 5, 15)
# array([5, 5, 10, 15, 15])
```

## Dicas
- Use `np.clip()` ou
- Use `np.where()` ou
- Use `np.minimum()` e `np.maximum()`

**Tempo estimado:** 7 minutos

In [11]:
def clipar_valores(arr, min_val, max_val):
    """
    Limita valores do array ao intervalo [min_val, max_val].

    Args:
        arr (np.ndarray): Array de entrada
        min_val (float): Valor mínimo
        max_val (float): Valor máximo

    Returns:
        np.ndarray: Array com valores limitados
    """
    # === SEU CÓDIGO AQUI ===

def clipar_valores(arr, minimo, maximo):
    """Limita os valores do array ao intervalo [minimo, maximo]."""
    return np.clip(arr, minimo, maximo)


    # === FIM DO SEU CÓDIGO ===

In [12]:
# Testar sua função
print("=== TESTE Q3 ===")
arr = np.array([-5, 0, 5, 10, 15, 20, 25])
resultado = clipar_valores(arr, 0, 20)
print(f"Original:  {arr}")
print(f"Clipped:   {resultado}")
print(f"\nValores no intervalo [0, 20]: {np.all((resultado >= 0) & (resultado <= 20))}")

grader.check("q3")

=== TESTE Q3 ===
Original:  [-5  0  5 10 15 20 25]
Clipped:   [ 0  0  5 10 15 20 20]

Valores no intervalo [0, 20]: True


q3 results: All test cases passed!

# Exercício 4: Encontrar Índices do Máximo

## Descrição
Dada uma matriz 2D, encontre os índices (linha, coluna) do maior valor.

## Exemplo
```python
matriz = np.array([[1, 5, 3],
                   [4, 2, 6]])
encontrar_indices_maximos(matriz)
# (1, 2)  # linha 1, coluna 2 (valor 6)
```

## Dicas
- Use `np.argmax()` para encontrar índice do máximo
- Use `np.unravel_index()` para converter índice flat para 2D

**Tempo estimado:** 8 minutos

In [13]:
def encontrar_indices_maximos(matriz):
    """
    Encontra índices (linha, coluna) do maior valor.

    Args:
        matriz (np.ndarray): Matriz 2D

    Returns:
        tuple: (linha, coluna) do máximo
    """
    # === SEU CÓDIGO AQUI ===

def encontrar_indices_maximos(matriz):
    """Retorna os índices (linha, coluna) do maior valor da matriz."""
    return np.unravel_index(np.argmax(matriz), matriz.shape)


    # === FIM DO SEU CÓDIGO ===


In [14]:
# Testar sua função
print("=== TESTE Q4 ===")
matriz = np.array([[10, 25, 15],
                   [30, 20, 35],
                   [12, 40, 18]])
print("Matriz:")
print(matriz)

idx = encontrar_indices_maximos(matriz)
print(f"\nÍndices do máximo: linha {idx[0]}, coluna {idx[1]}")
print(f"Valor máximo: {matriz[idx]}")

grader.check("q4")

=== TESTE Q4 ===
Matriz:
[[10 25 15]
 [30 20 35]
 [12 40 18]]

Índices do máximo: linha 2, coluna 1
Valor máximo: 40


q4 results: All test cases passed!

# Resumo

Nesta prática você trabalhou com:
- Criação de matrizes especiais
- Normalização de dados
- Operações de clipping
- Indexação avançada

**Pontuação total:** 10 pontos

Continue praticando!