# Aula 04 - Prática Independente: NumPy Avançado
**Curso:** Programação para Ciência de Dados  
**Aluno:** [Seu Nome Aqui]  
**Data:** [Data Atual]

## Instruções
1. Complete todos os exercícios marcados com `# === SEU CÓDIGO AQUI ===`
2. Execute as células de teste para verificar suas respostas
3. **Tempo estimado total:** 30 minutos

## Objetivo
Consolidar conhecimentos avançados de NumPy: manipulação de shape, álgebra linear, e concatenação.

In [11]:
# === CONFIGURAÇÃO INICIAL ===

!pip install --upgrade pip --quiet
!pip cache purge
!pip install otter-grader --no-cache-dir -q
!mkdir -p tests

print("Ambiente configurado!")

Files removed: 2 (38 kB)
Ambiente configurado!


In [12]:
%%writefile tests/q1.py
OK_FORMAT = True

test = {
    "name": "q1",
    "points": 2,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Shape correto
>>> import numpy as np
>>> arr = np.arange(24)
>>> resultado = reshape_3d(arr, 2, 3, 4)
>>> resultado.shape == (2, 3, 4)
True
""",
                    "hidden": False,
                    "locked": False
                },
                {
                    "code": r"""
>>> # Teste 2: Valores preservados
>>> import numpy as np
>>> arr = np.arange(24)
>>> resultado = reshape_3d(arr, 2, 3, 4)
>>> np.array_equal(resultado.flatten(), arr)
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Overwriting tests/q1.py


In [13]:
%%writefile tests/q2.py
OK_FORMAT = True

test = {
    "name": "q2",
    "points": 3,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Autovalores corretos
>>> import numpy as np
>>> A = np.array([[2, 0], [0, 3]], dtype=float)
>>> eigenvalues, eigenvectors = calcular_autovalores(A)
>>> len(eigenvalues) == 2
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Overwriting tests/q2.py


In [14]:
%%writefile tests/q3.py
OK_FORMAT = True

test = {
    "name": "q3",
    "points": 3,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Combina corretamente
>>> import numpy as np
>>> X = np.array([[1, 2], [3, 4]])
>>> y = np.array([[5], [6]])
>>> resultado = adicionar_coluna_labels(X, y)
>>> resultado.shape == (2, 3)
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Overwriting tests/q3.py


In [26]:
%%writefile tests/q4.py
OK_FORMAT = True

test = {
    "name": "q4",
    "points": 2,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Calcula distância corretamente
>>> import numpy as np
>>> p1 = np.array([0, 0])
>>> p2 = np.array([3, 4])
>>> dist = calcular_distancia_euclidiana(p1, p2)
>>> bool(abs(dist - 5.0) < 0.01)
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Overwriting tests/q4.py


In [16]:
import otter
import numpy as np

grader = otter.Notebook()
np.random.seed(42)

print("✓ Otter Grader carregado")
print("✓ NumPy importado")
print(f"✓ Versão NumPy: {np.__version__}")

✓ Otter Grader carregado
✓ NumPy importado
✓ Versão NumPy: 2.0.2


# Exercício 1: Reshape para 3D

## Descrição
Transforme um array 1D em um tensor 3D com as dimensões especificadas.
Isso é comum ao trabalhar com batches de imagens ou séries temporais.

## Exemplo
```python
arr = np.arange(24)  # 24 elementos
reshape_3d(arr, 2, 3, 4)  # (2, 3, 4)
# 2 batches, 3 linhas, 4 colunas
```

## Requisitos
- Use `reshape()`
- Verifique se o número total de elementos é compatível

**Tempo estimado:** 5 minutos

In [17]:
def reshape_3d(arr, dim1, dim2, dim3):
    """
    Reshape array 1D para 3D.

    Args:
        arr (np.ndarray): Array 1D
        dim1, dim2, dim3 (int): Dimensões desejadas

    Returns:
        np.ndarray: Array 3D com shape (dim1, dim2, dim3)
    """
    # === SEU CÓDIGO AQUI ===


    # === FIM DO SEU CÓDIGO ===


In [18]:
# Testar sua função
print("=== TESTE Q1 ===")
arr = np.arange(24)
print(f"Array 1D: shape {arr.shape}")
print(arr)

tensor = reshape_3d(arr, 2, 3, 4)
print(f"\nTensor 3D: shape {tensor.shape}")
print(tensor)
print(f"\nPrimeiro batch (2D):")
print(tensor[0])

grader.check("q1")

=== TESTE Q1 ===
Array 1D: shape (24,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Tensor 3D: shape (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Primeiro batch (2D):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


q1 results: All test cases passed!

# Exercício 2: Autovalores e Autovetores

## Descrição
Calcule os autovalores e autovetores de uma matriz quadrada.
Isso é fundamental para PCA, análise de estabilidade, e outras aplicações.

## Conceito
Para uma matriz A e autovetor v:
- A @ v = λ * v
- λ é o autovalor correspondente

## Exemplo
```python
A = np.array([[2, 0], [0, 3]])
eigenvalues, eigenvectors = calcular_autovalores(A)
# eigenvalues: [2, 3]
# eigenvectors: [[1, 0], [0, 1]]
```

## Dica
Use `np.linalg.eig()`

**Tempo estimado:** 7 minutos

In [19]:
def calcular_autovalores(A):
    """
    Calcula autovalores e autovetores.

    Args:
        A (np.ndarray): Matriz quadrada

    Returns:
        tuple: (eigenvalues, eigenvectors)
    """
    # === SEU CÓDIGO AQUI ===


    # === FIM DO SEU CÓDIGO ===


In [20]:
# Testar sua função
print("=== TESTE Q2 ===")
A = np.array([[4, 2],
              [2, 3]], dtype=float)
print("Matriz A:")
print(A)

eigenvalues, eigenvectors = calcular_autovalores(A)
print(f"\nAutovalores: {eigenvalues}")
print(f"\nAutovetores:")
print(eigenvectors)

# Verificar propriedade: A @ v = λ * v
print("\n=== VERIFICAÇÃO ===")
v = eigenvectors[:, 0]
lam = eigenvalues[0]
print(f"A @ v = {A @ v}")
print(f"λ * v = {lam * v}")
print(f"São iguais? {np.allclose(A @ v, lam * v)}")

grader.check("q2")

=== TESTE Q2 ===
Matriz A:
[[4. 2.]
 [2. 3.]]

Autovalores: [5.56155281 1.43844719]

Autovetores:
[[ 0.78820544 -0.61541221]
 [ 0.61541221  0.78820544]]

=== VERIFICAÇÃO ===
A @ v = [4.38364617 3.4226475 ]
λ * v = [4.38364617 3.4226475 ]
São iguais? True


q2 results: All test cases passed!

# Exercício 3: Concatenar Features e Labels

## Descrição
Em Machine Learning, às vezes precisamos combinar a matriz de features (X)
com o vetor de labels (y) em uma única matriz.

Adicione a coluna de labels como última coluna da matriz de features.

## Exemplo
```python
X = np.array([[1, 2],    # 2 amostras, 2 features
              [3, 4]])
y = np.array([[0],       # 2 labels
              [1]])
              
adicionar_coluna_labels(X, y)
# [[1, 2, 0],
#  [3, 4, 1]]
```

## Dicas
- Use `np.hstack()` ou `np.column_stack()` ou `np.c_[]`
- Certifique-se que y tem shape (n, 1) e não (n,)

**Tempo estimado:** 8 minutos

In [21]:
def adicionar_coluna_labels(X, y):
    """
    Adiciona coluna de labels às features.

    Args:
        X (np.ndarray): Matriz de features (n, m)
        y (np.ndarray): Vetor de labels (n, 1) ou (n,)

    Returns:
        np.ndarray: Matriz combinada (n, m+1)
    """
    # === SEU CÓDIGO AQUI ===


    # === FIM DO SEU CÓDIGO ===


In [22]:
# Testar sua função
print("=== TESTE Q3 ===")

# Exemplo 1: y como (n, 1)
X = np.array([[1.5, 2.3],
              [3.2, 4.1],
              [5.0, 6.8]])
y = np.array([[0],
              [1],
              [1]])

print("Features X:")
print(X)
print(f"Shape: {X.shape}")

print("\nLabels y:")
print(y)
print(f"Shape: {y.shape}")

resultado = adicionar_coluna_labels(X, y)
print("\nCombinado:")
print(resultado)
print(f"Shape: {resultado.shape}")

# Exemplo 2: y como (n,)
print("\n=== TESTE COM y 1D ===")
y_1d = np.array([0, 1, 1])
resultado2 = adicionar_coluna_labels(X, y_1d)
print(f"Shape resultado: {resultado2.shape}")
print(resultado2)

grader.check("q3")

=== TESTE Q3 ===
Features X:
[[1.5 2.3]
 [3.2 4.1]
 [5.  6.8]]
Shape: (3, 2)

Labels y:
[[0]
 [1]
 [1]]
Shape: (3, 1)

Combinado:
[[1.5 2.3 0. ]
 [3.2 4.1 1. ]
 [5.  6.8 1. ]]
Shape: (3, 3)

=== TESTE COM y 1D ===
Shape resultado: (3, 3)
[[1.5 2.3 0. ]
 [3.2 4.1 1. ]
 [5.  6.8 1. ]]


q3 results: All test cases passed!

# Exercício 4: Distância Euclidiana

## Descrição
Calcule a distância euclidiana entre dois pontos.
Essa métrica é fundamental para k-NN, clustering, e outros algoritmos.

## Fórmula
Para pontos p e q:
```
dist = √(Σ(pi - qi)²)
```

## Exemplo
```python
p1 = np.array([0, 0])
p2 = np.array([3, 4])
calcular_distancia_euclidiana(p1, p2)
# 5.0  (triângulo 3-4-5)
```

## Dicas
- Use `np.linalg.norm()` ou
- Calcule manualmente: `np.sqrt(np.sum((p1 - p2)**2))`

**Tempo estimado:** 5 minutos

In [23]:
def calcular_distancia_euclidiana(p1, p2):
    """
    Calcula distância euclidiana entre dois pontos.

    Args:
        p1 (np.ndarray): Primeiro ponto
        p2 (np.ndarray): Segundo ponto

    Returns:
        float: Distância euclidiana
    """
    # === SEU CÓDIGO AQUI ===


    # === FIM DO SEU CÓDIGO ===


In [27]:
# Testar sua função
print("=== TESTE Q4 ===")

# Teste 1: Triângulo 3-4-5
p1 = np.array([0, 0])
p2 = np.array([3, 4])
dist = calcular_distancia_euclidiana(p1, p2)
print(f"p1 = {p1}")
print(f"p2 = {p2}")
print(f"Distância: {dist} (esperado: 5.0)")

# Teste 2: Pontos 3D
print("\n=== TESTE 3D ===")
p3 = np.array([1, 2, 3])
p4 = np.array([4, 6, 8])
dist2 = calcular_distancia_euclidiana(p3, p4)
print(f"p3 = {p3}")
print(f"p4 = {p4}")
print(f"Distância: {dist2:.2f}")

# Teste 3: Mesmo ponto
print("\n=== TESTE DISTÂNCIA ZERO ===")
p5 = np.array([5, 5])
dist3 = calcular_distancia_euclidiana(p5, p5)
print(f"Distância para si mesmo: {dist3} (esperado: 0.0)")

grader.check("q4")

=== TESTE Q4 ===
p1 = [0 0]
p2 = [3 4]
Distância: 5.0 (esperado: 5.0)

=== TESTE 3D ===
p3 = [1 2 3]
p4 = [4 6 8]
Distância: 7.07

=== TESTE DISTÂNCIA ZERO ===
Distância para si mesmo: 0.0 (esperado: 0.0)


q4 results: All test cases passed!

# Resumo

Nesta prática você trabalhou com:
- Reshape para tensores 3D
- Autovalores e autovetores (álgebra linear)
- Concatenação de features e labels
- Distância euclidiana
- Aplicação prática: sistema de recomendação

Esses conceitos são essenciais para Machine Learning!

---

## Próximo Passo
Prepare-se para a **entrega quinzenal** que cobre as aulas 1-4!