# Aula 04 - Prática Guiada em Sala
**Curso:** Programação para Ciência de Dados  
**Aluno:** [Seu Nome Aqui]  
**Data:** [Data Atual]

## Instruções
1. Estes exercícios serão feitos **durante a aula** com orientação do professor
2. Complete todos os exercícios marcados com `# === SEU CÓDIGO AQUI ===`
3. Execute as células de teste para verificar suas respostas
4. **Tempo estimado:** 5-7 minutos por exercício
5. **Não precisa submeter** - este é apenas para prática em aula

## Objetivo
Exercícios simples e diretos para fixar os conceitos avançados de NumPy.

In [1]:
# === CONFIGURAÇÃO INICIAL ===

# Atualizar pip e limpar cache
!pip install --upgrade pip --quiet
!pip cache purge

# Instalar Otter Grader
!pip install otter-grader --no-cache-dir -q

# Criar diretório para testes
!mkdir -p tests

print("Otter Grader instalado!")
print("Diretório de testes criado!")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 13.0 MB/s eta 0:00:00
Files removed: 6 (1.8 MB)
Otter Grader instalado!
Diretório de testes criado!


In [2]:
%%writefile tests/p1.py
OK_FORMAT = True

test = {
    "name": "p1",
    "points": 1,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Verificar shape correto
>>> import numpy as np
>>> arr = np.arange(12)
>>> resultado = reshape_para_matriz(arr, 3, 4)
>>> resultado.shape == (3, 4)
True
""",
                    "hidden": False,
                    "locked": False
                },
                {
                    "code": r"""
>>> # Teste 2: Valores preservados
>>> import numpy as np
>>> arr = np.arange(12)
>>> resultado = reshape_para_matriz(arr, 3, 4)
>>> np.array_equal(resultado.flatten(), arr)
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/p1.py


In [3]:
%%writefile tests/p2.py
OK_FORMAT = True

test = {
    "name": "p2",
    "points": 1,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Transpor corretamente
>>> import numpy as np
>>> matriz = np.array([[1, 2, 3], [4, 5, 6]])
>>> resultado = transpor_matriz(matriz)
>>> resultado.shape == (3, 2)
True
""",
                    "hidden": False,
                    "locked": False
                },
                {
                    "code": r"""
>>> # Teste 2: Valores corretos
>>> import numpy as np
>>> matriz = np.array([[1, 2], [3, 4]])
>>> resultado = transpor_matriz(matriz)
>>> np.array_equal(resultado, np.array([[1, 3], [2, 4]]))
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/p2.py


In [4]:
%%writefile tests/p3.py
OK_FORMAT = True

test = {
    "name": "p3",
    "points": 1,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Produto matricial correto
>>> import numpy as np
>>> A = np.array([[1, 2], [3, 4]])
>>> B = np.array([[5, 6], [7, 8]])
>>> resultado = produto_matricial(A, B)
>>> np.array_equal(resultado, np.array([[19, 22], [43, 50]]))
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/p3.py


In [5]:
%%writefile tests/p4.py
OK_FORMAT = True

test = {
    "name": "p4",
    "points": 1,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Inversa correta
>>> import numpy as np
>>> A = np.array([[1, 2], [3, 4]], dtype=float)
>>> A_inv = calcular_inversa(A)
>>> resultado = A @ A_inv
>>> np.allclose(resultado, np.eye(2))
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/p4.py


In [6]:
%%writefile tests/p5.py
OK_FORMAT = True

test = {
    "name": "p5",
    "points": 1,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Solução correta
>>> import numpy as np
>>> A = np.array([[2, 1], [1, -1]], dtype=float)
>>> b = np.array([8, 1], dtype=float)
>>> x = resolver_sistema(A, b)
>>> np.allclose(A @ x, b)
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/p5.py


In [7]:
%%writefile tests/p6.py
OK_FORMAT = True

test = {
    "name": "p6",
    "points": 1,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Concatenação vertical
>>> import numpy as np
>>> a = np.array([[1, 2], [3, 4]])
>>> b = np.array([[5, 6], [7, 8]])
>>> resultado = concatenar_vertical(a, b)
>>> resultado.shape == (4, 2)
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/p6.py


In [8]:
%%writefile tests/p7.py
OK_FORMAT = True

test = {
    "name": "p7",
    "points": 1,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Stack com novo eixo
>>> import numpy as np
>>> a = np.array([1, 2, 3])
>>> b = np.array([4, 5, 6])
>>> resultado = empilhar_arrays(a, b)
>>> resultado.shape == (2, 3)
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Writing tests/p7.py


In [28]:
%%writefile tests/p8.py
OK_FORMAT = True

test = {
    "name": "p8",
    "points": 1,
    "suites": [
        {
            "cases": [
                {
                    "code": r"""
>>> # Teste 1: Salvar e carregar
>>> import numpy as np
>>> arr = np.array([1, 2, 3, 4, 5])
>>> resultado = salvar_carregar_array(arr, 'test.npy')
>>> import os
>>> os.path.exists('test.npy')
True
""",
                    "hidden": False,
                    "locked": False
                }
            ],
            "scored": True,
            "setup": "",
            "teardown": "",
            "type": "doctest"
        }
    ]
}

Overwriting tests/p8.py


In [10]:
# === CARREGAR OTTER GRADER ===

import otter
grader = otter.Notebook()

print("Otter Grader configurado!")
print(f"Versão: {otter.__version__}")
print("\nTestes públicos carregados: p1.py - p8.py")
print("\nPrática guiada NumPy Avançado!")

Otter Grader configurado!
Versão: 6.1.6

Testes públicos carregados: p1.py - p8.py

Prática guiada NumPy Avançado!


In [11]:
# === IMPORTAR NUMPY ===

import numpy as np

# Configurar exibição
np.set_printoptions(precision=2, suppress=True)

print(f"✓ NumPy versão: {np.__version__}")
print("✓ Pronto para começar!")

✓ NumPy versão: 2.0.2
✓ Pronto para começar!


# === PRÁTICA 1: RESHAPE ===

## Objetivo
Usar `reshape()` para reorganizar dimensões de array.

## Tarefa
Transformar array 1D em matriz 2D com dimensões especificadas.

## Retorno Esperado
Matriz com shape (linhas, colunas).

## Dicas
```python
# Reshape básico
arr = np.arange(12)
matriz = arr.reshape(3, 4)  # 3 linhas, 4 colunas

# Dimensão automática com -1
matriz = arr.reshape(3, -1)  # 3 linhas, ? colunas
```

In [12]:
def reshape_para_matriz(arr, linhas, colunas):
    """
    Transforma array 1D em matriz 2D.

    Args:
        arr (np.ndarray): Array 1D
        linhas (int): Número de linhas
        colunas (int): Número de colunas

    Returns:
        np.ndarray: Matriz com shape (linhas, colunas)
    """
    # === SEU CÓDIGO AQUI ===

    matriz = arr.reshape(linhas, colunas)

    return matriz

    # === FIM DO SEU CÓDIGO ===

In [13]:
# Testar função
arr = np.arange(12)
print(f"Array original: {arr}")
print(f"Shape: {arr.shape}")

# Reshape para diferentes dimensões
print("\n=== RESHAPE PARA DIFERENTES FORMAS ===")

matriz_3x4 = reshape_para_matriz(arr, 3, 4)
print(f"\n3x4:\n{matriz_3x4}")
print(f"Shape: {matriz_3x4.shape}")

matriz_2x6 = reshape_para_matriz(arr, 2, 6)
print(f"\n2x6:\n{matriz_2x6}")
print(f"Shape: {matriz_2x6.shape}")

matriz_4x3 = reshape_para_matriz(arr, 4, 3)
print(f"\n4x3:\n{matriz_4x3}")
print(f"Shape: {matriz_4x3.shape}")

# Verificar teste
grader.check("p1")

Array original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

=== RESHAPE PARA DIFERENTES FORMAS ===

3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)

2x6:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Shape: (2, 6)

4x3:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape: (4, 3)


p1 results: All test cases passed!

# === PRÁTICA 2: TRANSPOSE ===

## Objetivo
Transpor matriz (trocar linhas por colunas).

## Tarefa
Implementar transposição de matriz.

## Retorno Esperado
Matriz transposta.

## Dicas
```python
# Transpor matriz
matriz = np.array([[1, 2], [3, 4]])
transposta = matriz.T

# Ou usando função
transposta = np.transpose(matriz)
```

In [14]:
def transpor_matriz(matriz):
    """
    Transpõe uma matriz.

    Args:
        matriz (np.ndarray): Matriz 2D

    Returns:
        np.ndarray: Matriz transposta
    """
    # === SEU CÓDIGO AQUI ===

    transposta = matriz.T

    return transposta

    # === FIM DO SEU CÓDIGO ===

In [15]:
# Criar matriz de exemplo
matriz = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("=== TRANSPOSIÇÃO DE MATRIZ ===")
print(f"\nOriginal ({matriz.shape}):")
print(matriz)

# Transpor
transposta = transpor_matriz(matriz)

print(f"\nTransposta ({transposta.shape}):")
print(transposta)

# Verificar propriedade: (AT)T = A
dupla_transposta = transpor_matriz(transposta)
print(f"\nDupla transposta volta ao original:")
print(np.array_equal(matriz, dupla_transposta))

# Verificar teste
grader.check("p2")

=== TRANSPOSIÇÃO DE MATRIZ ===

Original ((2, 3)):
[[1 2 3]
 [4 5 6]]

Transposta ((3, 2)):
[[1 4]
 [2 5]
 [3 6]]

Dupla transposta volta ao original:
True


p2 results: All test cases passed!

# === PRÁTICA 3: PRODUTO MATRICIAL ===

## Objetivo
Realizar produto matricial (multiplicação de matrizes).

## Tarefa
Implementar multiplicação de duas matrizes.

## Retorno Esperado
Resultado do produto matricial A @ B.

## Dicas
```python
# Produto matricial
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Três formas equivalentes
C = A @ B              # Operador @ (preferido)
C = np.dot(A, B)       # Função dot
C = np.matmul(A, B)    # Função matmul
```

In [16]:
def produto_matricial(A, B):
    """
    Calcula produto matricial de A e B.

    Args:
        A (np.ndarray): Primeira matriz
        B (np.ndarray): Segunda matriz

    Returns:
        np.ndarray: Produto matricial A @ B
    """
    # === SEU CÓDIGO AQUI ===

    resultado = A @ B

    return resultado

    # === FIM DO SEU CÓDIGO ===

In [17]:
# Exemplo de multiplicação de matrizes
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print("=== PRODUTO MATRICIAL ===")
print(f"\nA ({A.shape}):")
print(A)
print(f"\nB ({B.shape}):")
print(B)

# Calcular produto
C = produto_matricial(A, B)

print(f"\nA @ B ({C.shape}):")
print(C)

# Comparar com multiplicação elemento-a-elemento
print("\n=== DIFERENÇA: @ vs * ===")
print(f"A @ B (matricial):\n{C}")
print(f"\nA * B (elemento-a-elemento):\n{A * B}")

# Verificar teste
grader.check("p3")

=== PRODUTO MATRICIAL ===

A ((2, 2)):
[[1 2]
 [3 4]]

B ((2, 2)):
[[5 6]
 [7 8]]

A @ B ((2, 2)):
[[19 22]
 [43 50]]

=== DIFERENÇA: @ vs * ===
A @ B (matricial):
[[19 22]
 [43 50]]

A * B (elemento-a-elemento):
[[ 5 12]
 [21 32]]


p3 results: All test cases passed!

# === PRÁTICA 4: INVERSA DE MATRIZ ===

## Objetivo
Calcular inversa de uma matriz.

## Tarefa
Implementar cálculo da inversa usando `np.linalg.inv()`.

## Retorno Esperado
Matriz inversa tal que A @ A_inv = I (identidade).

## Dicas
```python
# Calcular inversa
A = np.array([[1, 2], [3, 4]], dtype=float)
A_inv = np.linalg.inv(A)

# Verificar: A @ A_inv = I
I = A @ A_inv
print(I)  # Deve ser aproximadamente [[1, 0], [0, 1]]
```

In [18]:
def calcular_inversa(A):
    """
    Calcula a inversa de uma matriz.

    Args:
        A (np.ndarray): Matriz quadrada

    Returns:
        np.ndarray: Matriz inversa
    """
    # === SEU CÓDIGO AQUI ===

    A_inv = np.linalg.inv(A)

    return A_inv

    # === FIM DO SEU CÓDIGO ===

In [19]:
# Criar matriz
A = np.array([[1, 2],
              [3, 4]], dtype=float)

print("=== INVERSA DE MATRIZ ===")
print(f"\nMatriz A:")
print(A)

# Calcular inversa
A_inv = calcular_inversa(A)

print(f"\nMatriz A^-1:")
print(A_inv)

# Verificar: A @ A_inv = I
I = A @ A_inv
print(f"\nA @ A^-1 (deve ser identidade):")
print(I)

# Verificar se é aproximadamente identidade
I_esperada = np.eye(2)
print(f"\nÉ identidade? {np.allclose(I, I_esperada)}")

# Verificar teste
grader.check("p4")

=== INVERSA DE MATRIZ ===

Matriz A:
[[1. 2.]
 [3. 4.]]

Matriz A^-1:
[[-2.   1. ]
 [ 1.5 -0.5]]

A @ A^-1 (deve ser identidade):
[[1. 0.]
 [0. 1.]]

É identidade? True


p4 results: All test cases passed!

# === PRÁTICA 5: RESOLVER SISTEMA LINEAR ===

## Objetivo
Resolver sistema de equações lineares Ax = b.

## Tarefa
Usar `np.linalg.solve()` para encontrar x.

## Retorno Esperado
Vetor x que satisfaz Ax = b.

## Dicas
```python
# Sistema: 2x + y = 8
#          x - y = 1
A = np.array([[2, 1], [1, -1]], dtype=float)
b = np.array([8, 1], dtype=float)

# Resolver
x = np.linalg.solve(A, b)
# x = [3, 2] (x=3, y=2)
```

In [20]:
def resolver_sistema(A, b):
    """
    Resolve sistema linear Ax = b.

    Args:
        A (np.ndarray): Matriz de coeficientes
        b (np.ndarray): Vetor de termos independentes

    Returns:
        np.ndarray: Vetor solução x
    """
    # === SEU CÓDIGO AQUI ===

    x = np.linalg.solve(A, b)

    return x

    # === FIM DO SEU CÓDIGO ===

In [21]:
# Sistema de equações
# 2x + y = 8
# x - y = 1
A = np.array([[2, 1],
              [1, -1]], dtype=float)
b = np.array([8, 1], dtype=float)

print("=== RESOLVER SISTEMA LINEAR ===")
print("\nSistema:")
print("2x + y = 8")
print("x - y = 1")

# Resolver
x = resolver_sistema(A, b)

print(f"\nSolução:")
print(f"x = {x[0]}")
print(f"y = {x[1]}")

# Verificar solução
resultado = A @ x
print(f"\nVerificação:")
print(f"Ax = {resultado}")
print(f"b  = {b}")
print(f"Ax = b? {np.allclose(resultado, b)}")

# Verificar teste
grader.check("p5")

=== RESOLVER SISTEMA LINEAR ===

Sistema:
2x + y = 8
x - y = 1

Solução:
x = 3.0
y = 2.0

Verificação:
Ax = [8. 1.]
b  = [8. 1.]
Ax = b? True


p5 results: All test cases passed!

# === PRÁTICA 6: CONCATENAÇÃO VERTICAL ===

## Objetivo
Concatenar arrays verticalmente (empilhar linhas).

## Tarefa
Usar `np.vstack()` ou `np.concatenate()` com axis=0.

## Retorno Esperado
Array resultante da concatenação vertical.

## Dicas
```python
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Duas formas equivalentes
c = np.vstack([a, b])
c = np.concatenate([a, b], axis=0)
```

In [22]:
def concatenar_vertical(a, b):
    """
    Concatena dois arrays verticalmente.

    Args:
        a (np.ndarray): Primeiro array
        b (np.ndarray): Segundo array

    Returns:
        np.ndarray: Array concatenado verticalmente
    """
    # === SEU CÓDIGO AQUI ===

    resultado = np.vstack([a, b])

    return resultado

    # === FIM DO SEU CÓDIGO ===

In [23]:
# Arrays de exemplo
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[7, 8, 9],
              [10, 11, 12]])

print("=== CONCATENAÇÃO VERTICAL ===")
print(f"\nArray A ({a.shape}):")
print(a)
print(f"\nArray B ({b.shape}):")
print(b)

# Concatenar
resultado = concatenar_vertical(a, b)

print(f"\nResultado ({resultado.shape}):")
print(resultado)

# Aplicação prática: adicionar novas amostras
print("\n💡 Uso prático: adicionar novos dados ao dataset")
print("   Dataset original: 2 amostras")
print("   Novos dados: 2 amostras")
print("   Dataset final: 4 amostras")

# Verificar teste
grader.check("p6")

=== CONCATENAÇÃO VERTICAL ===

Array A ((2, 3)):
[[1 2 3]
 [4 5 6]]

Array B ((2, 3)):
[[ 7  8  9]
 [10 11 12]]

Resultado ((4, 3)):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

💡 Uso prático: adicionar novos dados ao dataset
   Dataset original: 2 amostras
   Novos dados: 2 amostras
   Dataset final: 4 amostras


p6 results: All test cases passed!

# === PRÁTICA 7: STACK (EMPILHAR) ===

## Objetivo
Empilhar arrays criando nova dimensão.

## Tarefa
Usar `np.stack()` para criar novo eixo.

## Retorno Esperado
Array com dimensão adicional.

## Dicas
```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack ao longo de novo eixo 0
c = np.stack([a, b], axis=0)
# [[1, 2, 3],
#  [4, 5, 6]]
```

In [24]:
def empilhar_arrays(a, b):
    """
    Empilha dois arrays criando nova dimensão.

    Args:
        a (np.ndarray): Primeiro array
        b (np.ndarray): Segundo array

    Returns:
        np.ndarray: Arrays empilhados
    """
    # === SEU CÓDIGO AQUI ===

    resultado = np.stack([a, b], axis=0)

    return resultado

    # === FIM DO SEU CÓDIGO ===

In [25]:
# Vetores 1D
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("=== STACK: CRIAR NOVA DIMENSÃO ===")
print(f"\nArray A ({a.shape}): {a}")
print(f"Array B ({b.shape}): {b}")

# Empilhar
resultado = empilhar_arrays(a, b)

print(f"\nResultado ({resultado.shape}):")
print(resultado)

# Comparar com vstack
print("\n=== DIFERENÇA: stack vs vstack ===")
print(f"stack (cria nova dim): shape {resultado.shape}")
vstack_resultado = np.vstack([a, b])
print(f"vstack (usa dim exist): shape {vstack_resultado.shape}")
print(f"\nResultados iguais? {np.array_equal(resultado, vstack_resultado)}")

# Verificar teste
grader.check("p7")

=== STACK: CRIAR NOVA DIMENSÃO ===

Array A ((3,)): [1 2 3]
Array B ((3,)): [4 5 6]

Resultado ((2, 3)):
[[1 2 3]
 [4 5 6]]

=== DIFERENÇA: stack vs vstack ===
stack (cria nova dim): shape (2, 3)
vstack (usa dim exist): shape (2, 3)

Resultados iguais? True


p7 results: All test cases passed!

# === PRÁTICA 8: SALVAR E CARREGAR ===

## Objetivo
Salvar array em disco e carregar novamente.

## Tarefa
Usar `np.save()` para salvar e `np.load()` para carregar.

## Retorno Esperado
Array carregado idêntico ao original.

## Dicas
```python
# Salvar
arr = np.array([1, 2, 3, 4, 5])
np.save('dados.npy', arr)

# Carregar
arr_loaded = np.load('dados.npy')

# Verificar igualdade
np.array_equal(arr, arr_loaded)  # True
```

In [26]:
def salvar_carregar_array(arr, filename):
    """
    Salva array em disco e carrega de volta.

    Args:
        arr (np.ndarray): Array para salvar
        filename (str): Nome do arquivo

    Returns:
        np.ndarray: Array carregado
    """
    # === SEU CÓDIGO AQUI ===

    # Salvar
    np.save(filename, arr)

    # Carregar
    arr_loaded = np.load(filename)

    return arr_loaded

    # === FIM DO SEU CÓDIGO ===

In [29]:
# Criar array de exemplo
arr_original = np.random.randn(5, 3)

print("=== SALVAR E CARREGAR ARRAYS ===")
print(f"\nArray original:")
print(arr_original)
print(f"Shape: {arr_original.shape}")
print(f"Dtype: {arr_original.dtype}")

# Salvar e carregar
arr_loaded = salvar_carregar_array(arr_original, 'test_array.npy')

print(f"\nArray carregado:")
print(arr_loaded)
print(f"Shape: {arr_loaded.shape}")
print(f"Dtype: {arr_loaded.dtype}")

# Verificar igualdade
print(f"\n=== VERIFICAÇÃO ===")
print(f"Arrays são iguais? {np.array_equal(arr_original, arr_loaded)}")
print(f"Shapes iguais? {arr_original.shape == arr_loaded.shape}")
print(f"Dtypes iguais? {arr_original.dtype == arr_loaded.dtype}")

# Verificar se arquivo foi criado
import os
print(f"\nArquivo existe? {os.path.exists('test_array.npy')}")
if os.path.exists('test_array.npy'):
    size = os.path.getsize('test_array.npy')
    print(f"Tamanho do arquivo: {size} bytes")

# Verificar teste
grader.check("p8")

=== SALVAR E CARREGAR ARRAYS ===

Array original:
[[ 0.08  0.59  0.05]
 [-0.43  1.44  0.55]
 [ 0.33  0.8  -0.48]
 [ 0.33  1.87 -0.4 ]
 [ 0.48 -0.9  -0.2 ]]
Shape: (5, 3)
Dtype: float64

Array carregado:
[[ 0.08  0.59  0.05]
 [-0.43  1.44  0.55]
 [ 0.33  0.8  -0.48]
 [ 0.33  1.87 -0.4 ]
 [ 0.48 -0.9  -0.2 ]]
Shape: (5, 3)
Dtype: float64

=== VERIFICAÇÃO ===
Arrays são iguais? True
Shapes iguais? True
Dtypes iguais? True

Arquivo existe? True
Tamanho do arquivo: 248 bytes


p8 results: All test cases passed!

# === RESUMO DA PRÁTICA GUIADA ===

## Conceitos Praticados

### Prática 1 - Reshape
- Reorganizar dimensões de arrays
- Transformar 1D em 2D e vice-versa
- Usar -1 para dimensão automática

### Prática 2 - Transpose
- Trocar linhas por colunas
- Propriedade: (AT)T = A
- Essencial para álgebra linear

### Prática 3 - Produto Matricial
- Multiplicação de matrizes com @
- Diferença entre @ e *
- Verificar compatibilidade de dimensões

### Prática 4 - Inversa
- Calcular matriz inversa
- Verificar: A @ A_inv = I
- Aplicação em resolver sistemas

### Prática 5 - Sistema Linear
- Resolver Ax = b
- np.linalg.solve() é mais eficiente que inversa
- Verificar solução

### Prática 6 - Concatenação Vertical
- Empilhar arrays por linhas
- vstack() ou concatenate(axis=0)
- Adicionar amostras a datasets

### Prática 7 - Stack
- Criar nova dimensão
- Diferença entre stack e concatenate
- Útil para criar batches

### Prática 8 - I/O
- Salvar arrays com save()
- Carregar com load()
- Formato .npy preserva tudo

---

## Próximos Passos

Agora você está pronto para:
1. Fazer os exercícios da **prática independente**
2. Trabalhar com manipulações complexas de arrays
3. Aplicar álgebra linear em problemas reais
4. Preparar a **entrega quinzenal**

---

## Conceitos-Chave

- **reshape(-1, x):** NumPy calcula dimensão automaticamente
- **@ é produto matricial**, * é elemento-a-elemento
- **Transpor:** Trocar linhas por colunas
- **solve()** é melhor que calcular inversa
- **stack cria nova dimensão**, concatenate usa existente
- **.npy preserva** dtype e shape exatos
- **Sempre verificar** compatibilidade de dimensões

**Bom trabalho!**